ALTER TABLE "CommunityPost" ADD COLUMN IF NOT EXISTS "emailConsentGiven" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CommunityPost" ADD COLUMN IF NOT EXISTS "emailApproved" BOOLEAN NOT NULL DEFAULT false;
